theme: jekyll-theme-minimal
title: Liang Zhang
description: SphereEx 创始人 & CEO，Apache Member，Apache ShardingSphere、ElasticJob 创始人 & 项目管理委员会主席，腾讯云 TVP、微软 MVP。<br/><br/>热爱开源，擅长以 Java 为主分布式架构，推崇优雅代码。目前主要精力投入在将 Apache ShardingSphere 打造为业界一流的金融级分布式数据库解决方案之上；2019 年出版书籍《未来架构——从服务化到云原生》；2020年度十大开源杰出贡献人物，2021年度海纳奖“分布式数据库十大先锋人物”。
show_downloads: false
logo: images/avatar.jpeg
