theme: jekyll-theme-minimal
title: Liang Zhang
description:  *SphereEx Co-Founder & CEO, Apache Member, Apache ShardingSphere, ElasticJob Founder & PMC Chair, Tencent Cloud TVP, Microsoft MVP.<br/><br/>Zhang is enthusiastic about open source, a thought leader in the field of distributed architectures based on Java, and is always striving to promote clean code. Currently, he focuses on turning Apache ShardingSphere into an industry-leading financial-grade distributed database solution. <br/>His book "Future Architecture: From Service to Cloud Native" was published in 2019, and was well received by both critics and the community. <br/>Zhang was awarded the title of "Top Ten Open Source Contributor of 2020" and "Top Ten Distributed Database Pioneers of 2021" by Haina Industry Co., Ltd.* 
show_downloads: false
logo: images/avatar.jpeg


